### ISSUE TITLE
SkyQ

### ISSUE THREAD

**Issue by tonypartridge** [AdamSwinden/homebridge-sky-plus#3]
Have you tested this with SkyQ?

**Comment by AdamSwinden** [comment]
No, I haven't tested it with SkyQ. But my guess is that it's unlikely to work because it's completely different hardware.

**Comment by danc91** [comment]
I've tried it with SkyQ, doesn't work.. :(

**Comment by LupoLoopy** [comment]
https://github.com/dalhundal/sky-remote/issues/4

It's easily fixed by changing port number, so I read?

**Comment by stuartridout** [comment]
Did you get it working @LupoLoopy by changing the port number?   Where do you change it?

**Comment by LupoLoopy** [comment]
You'd need to change it in the code - specifically the fork of the Sky node JS resources this project references (and I believe forks).

Although you and I could create our own personal development forks, it wouldn't help the wider user base.
